### ISSUE TITLE
No binary file after make

### ISSUE THREAD

**Issue by maoxs2** [alloy-project/alloy#17]
environment: Ubuntu16.04

I cannot find the wallet binary file anywhere

**Comment by AnythingTechPro** [comment]
Hello, did compilation fail?

**Comment by maoxs2** [comment]
I just see the fatal at beginning of `make` :
fatal: No names found, cannot describe anything.
CMake Warning at src/version.cmake:3 (message):
Cannot determine current revision. Make sure that you are building either
from a Git working tree or from a source archive.

**Comment by AnythingTechPro** [comment]
Refer to the Building guide on the Wiki for building from the source code. https://github.com/alloy-project/alloy/wiki/Building
