### ISSUE TITLE
Pool configuration

### ISSUE THREAD

**Issue by sanich-rd** [alloy-project/alloy#23]
Please tell me I have a pool of ETN want to remake XAO. Is it possible to help with the settings. You can personally e-mail. Sanich-rd1@yandex.ru. Here is the configuration for ETN.

{
    "coin": "electroneum",
    "symbol": "ETN",
    "coinUnits": 100,
    "coinDifficultyTarget": 60,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 4444,
                "difficulty": 1000,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 20000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 100000,
                "desc": "High end hardware"
            },
            {
                "port": 8888,
                "difficulty": 20000,
                "desc": "Hidden port",
                "hidden": true
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 10,
        "mixin": 0,
        "transferFee": 1,
        "minPayment": 10000,
        "maxTransactionAmount": 0,
        "denomination": 100
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 10,
        "poolFee": 1,
        "devDonation": 0.1,
        "coreDevDonation": 0.1,
        "extraFeaturesDevDonation":0.1
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "xxx"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 26968
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 26969
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}

**Comment by sanich-rd** [comment]
Pool is up and running. Can be the first pool!

**Comment by sanich-rd** [comment]
If all the test and everything will work ready to buy a decent service capacity.

**Comment by nighthawk18** [comment]
{
    "coin": "Alloy",
    "symbol": "XAO",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 180,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "MYADDRESS",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,

      "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "CPU Rigs"
            },
         {
                "port": 5555,
                "difficulty": 10000,
                "desc": "GPU Rigs"
            },

         {
                "port": 7777,
                "difficulty": 500000,
                "desc": "Multiple GPU Rigs over 50KH/s+ or use Fixed Diff"
            }

        ],



"varDiff": {
            "minDiff": 100,
            "maxDiff": 50000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },

        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 20,
            "invalidPercent": 25,
            "checkThreshold": 30
        },

  "slushMining": {
            "enabled": false,
            "weight": 120,
            "lastBlockCheckRate": 1
        }

    },

    "payments": {
        "enabled": true,
        "interval": 180,
        "maxAddresses": 40,
        "mixin": 0,
        "transferFee": 10000000000,
        "minPayment": 2000000000000,
        "maxTransactionAmount": 1000000000000000,
        "denomination": 1000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 30,
        "poolFee": 1.0,
        "devDonation": 0,
        "coreDevDonation": 0.0,
        "extraFeaturesDevDonation":0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 10,
        "port": 8118,
        "blocks": 30,
        "payments": 30,
        "password": "MYPASSWORD"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 1811
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8070
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },


    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}
