### ISSUE TITLE
CRYPTONOTE_MEMPOOL_TX_LIVETIME

### ISSUE THREAD

**Issue by nighthawk18** [alloy-project/alloy#24]
Suggest #define CRYPTONOTE_MEMPOOL_TX_LIVETIME be updated to 6 * 60 * 60 to improve user experience.

**Comment by AnythingTechPro** [comment]
https://github.com/alloy-project/alloy/commit/daea73ff0e2caf9a0cb6cdf9d1bdfefe398d8c33
