### ISSUE TITLE
Need prev_hash in getblocktemplate

### ISSUE THREAD

**Issue by nighthawk18** [alloy-project/alloy#4]
Newer pool software depends on certain return variables that Alloy lacks. One of these is the prev_hash variable which is part of the return of the getblocktemplate RPC call. 

It would be very helped for the devs to change the getblocktemplate to return these additional values so better quality pool software can be run. It should be a trivial update.

getblocktemplate
Inputs:

wallet_address - string; Address of wallet to receive coinbase transactions if block is successfully mined.
reserve_size - unsigned int; Reserve size.
Outputs:

blocktemplate_blob - string; Blob on which to try to mine a new block.
difficulty - unsigned int; Difficulty of next block.
height - unsigned int; Height on which to mine.
prev_hash - string; Hash of the most recent block on which to mine the next block.
reserved_offset - unsigned int; Reserved offset.

**Comment by nighthawk18** [comment]
Example change:    
core_rpc_server.cpp
 +    blobdata hashing_blob = get_block_hashing_blob(b);
 +    res.prev_hash = string_tools::pod_to_hex(b.prev_id);
      res.blocktemplate_blob = string_tools::buff_to_hex_nodelimer(block_blob);
 +    res.blockhashing_blob =  string_tools::buff_to_hex_nodelimer(hashing_blob);
      res.status = CORE_RPC_STATUS_OK;
      return true;

core_rpc_server_commands_defs.h
+      std::string prev_hash;
        blobdata blocktemplate_blob;
 +      blobdata blockhashing_blob;
        std::string status;
  
        BEGIN_KV_SERIALIZE_MAP()
          KV_SERIALIZE(difficulty)
          KV_SERIALIZE(height)
          KV_SERIALIZE(reserved_offset)
 +        KV_SERIALIZE(prev_hash)
          KV_SERIALIZE(blocktemplate_blob)
 +        KV_SERIALIZE(blockhashing_blob)

**Comment by alloy-project** [comment]
https://github.com/alloy-project/alloy/commit/06bdcd7b7277fab3f08f72af7dd7a70bd572d607

**Comment by alloy-project** [comment]
Please test it to ensure it works properly, before using it.

**Comment by nighthawk18** [comment]
Doesn't seem to returning it in the rpc call. I noticed you are using "response" and "responce". May be a variable assignment issue.
 
:/opt/alloy# grep -r prev_hash
 src/Rpc/RpcServer.cpp:  responce.prev_hash = Common::podToHex(blk.previousBlockHash);
src/Rpc/CoreRpcServerCommandsDefinitions.h:  std::string prev_hash;
src/Rpc/CoreRpcServerCommandsDefinitions.h:    KV_MEMBER(prev_hash)


/opt/pool# curl -X POST http://127.0.0.1:1811/json_rpc  -H 'Content-Type: application/json'  -d '{   "jsonrpc": "2.0",    "id": "0",    "method": "getblocktemplate", "params": {      "wallet_address": "1QSUhMNVbG3GPf48HM3kDXXUss6Q8hAqx5vEhMAxYuLFCr3QMF11xRxHMMAdRboLeLhtxkMJytQZdXBvnejS1dxtJGe77DJ",      "reserve_size": 60   }}'
{"id":"0","jsonrpc":"2.0","result":{"blocktemplate_blob":"0100c0b9d1d20521217936b8c461613cd5d2a3107df162d73ff2e48e0db52d836cca35185a16060000000001aa1d01ffee1c0280a0b6cef78502028a708218769041d0dac6e4c3e9ab74c546b694ddb8a2d2eea64a73fdbc7325fc80c089a9a2f50f029a65722785b00a5bc175b5d1c57a57282a77ab13899fa8417d675d6d150854995f016d0f7fa8c103359c8b2ab5b42da2c07d88a78b3c8a06e7037075924812cf379c023c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":71156947,"height":3694,"reserved_offset":168,"status":"OK"}}

**Comment by nighthawk18** [comment]
testing pool

**Comment by nighthawk18** [comment]
Pool works. Thanks for the quick response and amazing work, devs!
